### PR TITLE
fix: stop reset health & armor when model changes

### LINKED ISSUE #32: Health reset
its health will be reset after you close menu ? 
or just for me ?

### PR DESCRIPTION
**Pull request by franfdezmorales**
fixed #32 and #28

### CODE REVIEW

File: game/src/client/index.ts [hunk 1]
```diff
@@ -177,16 +177,18 @@ export async function setPlayerModel(model: string): Promise<void> {
     await Delay(0);
   }
 
-  SetPlayerModel(PlayerId(), model);
+  const playerPed = PlayerPedId();
```
Comment (pedr0fontoura) [inline game/src/client/index.ts:180]: This needs to be cached after setting the new player model because the SetPlayerModel native changes the player ped id.

**Review by pedr0fontoura — CHANGES_REQUESTED** [review]

File: game/src/client/index.ts (hunk 1 above)
Comment (franfdezmorales) [reply game/src/client/index.ts:180]: Its setted on function `setPedStats` on utils/index.ts

Comment (franfdezmorales) [reply game/src/client/index.ts:180]: Didnt understand, sorry, it is cached after setting new model.

Comment (pedr0fontoura) [reply game/src/client/index.ts:180]: When you set the player model on line 183, the PlayerPedId() changes, so when you pass the playerPed cached on 180 to isPedFreemodeModel on 168, or SetPedDefaultComponentVariation on 187 you're passing an invalid ped id.

Comment (franfdezmorales) [reply game/src/client/index.ts]: Yeah, nvm, fixed on new commit

**Review by pedr0fontoura — APPROVED** [review]
Everything is ok. Thanks for contributing.
